version: "2"         # required to adjust maintainability checks
checks:
  # Duplication overrides -- affects all languages
  similar-code:
    config:
      threshold: 75
  identical-code:
    config:
      threshold: 100
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 4
