files:
  - source: /source/**/en-us.json
    translation: /source/**/%locale%.json
  - source: /source/OptimaJet.DWKit.StarterApplication/Metadata/Localization/base.json
    translation: >-
      /source/OptimaJet.DWKit.StarterApplication/Metadata/Localization/%locale%.json
