files:
  - source: /source/**/en-us.json
    translation: /source/**/%locale%.json
    languages_mapping:
      locale:
        es-PE: es-pe
        fr: fr-fr
  - source: /source/OptimaJet.DWKit.StarterApplication/Metadata/Localization/base.json
    translation: >-
      /source/OptimaJet.DWKit.StarterApplication/Metadata/Localization/%locale%.json
