name: Scriptoria CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get environment info
        run: |
          echo Python version
          python --version
          pip --version
          echo
          echo Node version
          node --version
          yarn --version
          npm --version
          echo
          echo Docker version
          docker --version
          docker-compose --version

      - name: Frontend linting
        run: ./run yarn && ./run yarn lint --quiet

      - name: Frontend tests
        run: |
          COVERAGE=true ./run yarn && ./run yarn test:ci

      - name: Backend Tests
        run: |
          echo "building docker containers..."
          time ( ./run ci:build > /dev/null 2>&1 )
          echo "docker containers built!"
          echo "Running the backend commands..."
          time ( ./run ci:api )       
